/* AUTO-GENERATED FILE. DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found. It
 * should not be modified by hand.
 */

package com.example.astroapp;

public final class R {
  public static final class id {
    public static final int camera_preview=0x7f010000;
    public static final int capture_button=0x7f010001;
    public static final int controls_panel=0x7f010002;
    public static final int exposure_info=0x7f010003;
    public static final int frame_counter=0x7f010004;
    public static final int iso_wheel=0x7f010005;
    public static final int last_capture_preview=0x7f010006;
    public static final int session_settings_info=0x7f010007;
    public static final int shutter_wheel=0x7f010008;
    public static final int status_panel=0x7f010009;
    public static final int status_text=0x7f01000a;
  }
  public static final class layout {
    public static final int activity_main=0x7f020000;
  }
  public static final class string {
    public static final int app_name=0x7f030000;
  }
}